export const UPDATE_SYSINFO_MUTATION = "UPDATE_SYSINFO_MUTATION";
export const UPDATE_EVENTLIST_MUTATION = "UPDATE_EVENT_MUTATION";
export const UPDATE_NODELIST_MUTATION = "UPDATE_NODELIST_MUTATION";
export const UPDATE_BASICINFO_MUTATION = "UPDATE_BASICINFO_MUTATION";
export const UPDATE_FLWOINFO_MUTATION = "UPDATE_FLWOINFO_MUTATION";

export const INIT_HOME_ACTION = "INIT_HOME_ACTION";
export const UPDATE_SYSINFO_ACTION = "UPDATE_SYSINFO_ACTION";
export const UPDATE_EVENTLIST_ACTION = "UPDATE_EVENT_ACTION";
export const UPDATE_NODELIST_ACTION = "UPDATE_NODELIST_ACTION";
export const UPDATE_BASICINFO_ACTION = "UPDATE_BASICINFO_ACTION";
export const UPDATE_FLWOINFO_ACTION = "UPDATE_FLWOINFO_ACTION";
