export const UPDATE_SYSINFO_MUTATION = "UPDATE_SYSINFO_MUTATION";
export const UPDATE_EVENTLIST_MUTATION = "UPDATE_EVENT_MUTATION";
export const UPDATE_NODELIST_MUTATION = "UPDATE_NODELIST_MUTATION";
export const UPDATE_NODESTATISTICS_MUTATION = "UPDATE_NODESTATISTICS_MUTATION";

export const UPDATE_NETINFO_MUTATION = "UPDATE_NETINFO_MUTATION";
export const UPDATE_FLWOINFO_MUTATION = "UPDATE_FLWOINFO_MUTATION";
export const UPDATE_LINKLIST_MUTATION = "UPDATE_LINKLIST_MUTATION";

export const INIT_HOME_ACTION = "INIT_HOME_ACTION";
export const UPDATE_SYSINFO_ACTION = "UPDATE_SYSINFO_ACTION";
export const UPDATE_EVENTLIST_ACTION = "UPDATE_EVENT_ACTION";
export const UPDATE_NODELIST_ACTION = "UPDATE_NODELIST_ACTION";
export const UPDATE_NODESTATISTICS_ACTION = "UPDATE_NODESTATISTICS_ACTION";
export const UPDATE_NETINFO_ACTION = "UPDATE_NETINFO_ACTION";
export const UPDATE_FLWOINFO_ACTION = "UPDATE_FLWOINFO_ACTION";
export const UPDATE_LINKLIST_ACTION = "UPDATE_LINKLIST_ACTION";
