export const UPDATE_TIMENODESTATISTICS_MUTATION =
  "UPDATE_TIMENODESTATISTICS_MUTATION";
export const UPDATE_TIMELIST_MUTATION = "UPDATE_TIMELIST_MUTATION";
export const UPDATE_TIMESTATION_MUTATION = "UPDATE_TIMESTATION_MUTATION";
export const UPDATE_NODELIST_MUTATION = "UPDATE_NODELIST_MUTATION";
export const UPDATE_LINKLIST_MUTATION = "UPDATE_LINKLIST_MUTATION";

export const UPDATE_TIMENODESTATISTICS_ACTION =
  "UPDATE_TIMENODESTATISTICS_ACTION";
export const UPDATE_TIMELIST_ACTION = "UPDATE_TIMELIST_ACTION";
export const UPDATE_TIMESTATION_ACTION = "UPDATE_TIMESTATION_ACTION";
export const UPDATE_NODELIST_ACTION = "UPDATE_NODELIST_ACTION";
export const UPDATE_LINKLIST_ACTION = "UPDATE_LINKLIST_ACTION";
