export const UPDATE_NETINFO_MUTATION = "UPDATE_NETINFO_MUTATION";
export const UPDATE_BANDINFO_MUTATION = "UPDATE_BANDINFO_MUTATION";
export const UPDATE_NODEINFO_MUTATION = "UPDATE_NODEINFO_MUTATION";
export const UPDATE_NODEBAND_MUTATION = "UPDATE_NODEBAND_MUTATION";
export const UPDATE_LINKINFO_MUTATION = "UPDATE_LINKINFO_MUTATION";
export const UPDATE_NODES_MUTATION = "UPDATE_NODES_MUTATION";
export const UPDATE_LINKS_MUTATION = "UPDATE_LINKS_MUTATION";

export const INIT_LIGHT_ACTION = "INIT_LIGHT_ACTION";
export const UPDATE_NETINFO_ACTION = "UPDATE_NETINFO_ACTION";
export const UPDATE_BANDINFO_ACTION = "UPDATE_BANDINFO_ACTION";
export const UPDATE_NODEINFO_ACTION = "UPDATE_NODEINFO_ACTION";
export const UPDATE_NODEBAND_ACTION = "UPDATE_NODEBAND_ACTION";
export const UPDATE_LINKINFO_ACTION = "UPDATE_LINKINFO_ACTION";
export const UPDATE_NODES_ACTION = "UPDATE_NODES_ACTION";
export const UPDATE_LINKS_ACTION = "UPDATE_LINKS_ACTION";
