export const UPDATE_NETINFO_MUTATION = "UPDATE_NETINFO_MUTATION";
export const UPDATE_NODEINFO_MUTATION = "UPDATE_NODEINFO_MUTATION";
export const UPDATE_NODEBAND_MUTATION = "UPDATE_NODEBAND_MUTATION";
export const UPDATE_LINKINFO_MUTATION = "UPDATE_LINKINFO_MUTATION";
export const UPDATE_NODELIST_MUTATION = "UPDATE_NODELIST_MUTATION";
export const UPDATE_LINKLIST_MUTATION = "UPDATE_LINKLIST_MUTATION";

export const UPDATE_NETINFO_ACTION = "UPDATE_NETINFO_ACTION";
export const UPDATE_BANDINFO_ACTION = "UPDATE_BANDINFO_ACTION";
export const UPDATE_NODEINFO_ACTION = "UPDATE_NODEINFO_ACTION";
export const UPDATE_NODEBAND_ACTION = "UPDATE_NODEBAND_ACTION";
export const UPDATE_LINKINFO_ACTION = "UPDATE_LINKINFO_ACTION";
export const UPDATE_NODELIST_ACTION = "UPDATE_NODELIST_ACTION";
export const UPDATE_LINKLIST_ACTION = "UPDATE_LINKLIST_ACTION";
